language: node_js
node_js:
  - 'stable'

sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - npm install -g --silent firebase-tools
  - npm install -g --silent @angular/cli

install:
  - npm install
  - ng build --prod

script:
  - npm run test:ci

after_success:
  - test $TRAVIS_BRANCH="master" && test $TRAVIS_PULL_REQUEST="false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive
