language: 'node_js'
node_js:
 - '10'
addons:
  chrome: 'stable'
cache:
  directories:
  - node_modules
before_install:
 - npm install @angular/cli -g
 - npm install typescript -g
 - npm install karma -g
install:
 - npm install
script:
 - npm run lint
 - npm run test
 - npm run build
