dist: trusty
sudo: true

language: node_js
node_js:
  - "stable"

addons:
  chrome: stable

cache:
  directories:
  - node_modules

before_install:
  - npm install -g @angular/cli
  - npm install -g karma

install:
 - npm install

script:
  - npm run test
